### ISSUE TITLE
Message feature: the reply message jumps its rank, going before the sent message.

### ISSUE THREAD

**Issue by susanatqlc** [confidantstation/General-issue#12]
聊天信息跳跃: 回复的信息会到发送的信息前面

**Comment by qlinkDev** [comment]
别人给你发了一个消息A，然后你回复这个消息（记录为消息B），是在当前聊天页面 B显示在A上面？还是出去这个聊天界面再进来，B显示在A前面？

**Comment by susanatqlc** [comment]
别人给你发了一个消息A，然后你回复这个消息（记录为消息B），回复之后，B动起来了，跳到了A前面。然后保持了B在A前面。当然发生的速度非常快。

**Comment by qlinkDev** [comment]
退出这个聊天界面 再进来，b还在a前面吗？
