### ISSUE TITLE
When reply emails, the senders' email address appear as "to" box, which are the recipients' address

### ISSUE THREAD

**Issue by susanatqlc** [confidantstation/General-issue#4]
回复邮件的时候，发件人的邮件地址为目标邮件地址
![receive](https://user-images.githubusercontent.com/54051334/62992099-bf8a8e80-be84-11e9-8e1b-a1f30373b611.jpeg)
![reply](https://user-images.githubusercontent.com/54051334/62992106-c6190600-be84-11e9-8841-dffbf8ddaa4a.jpeg)

**Comment by qlinkDev** [comment]
Version 1.0.8 ，build 1289 is done
