### ISSUE TITLE
Content readable when reply received

### ISSUE THREAD

**Issue by suuuju** [confidantstation/General-issue#9]
1. Email sent via Confidant and it was encrypted, however when one email recipient replied to the email, all email thread is readable (including the previously encrypted part) . 'a
2. Email sent via Confidant, while the email is not listed in 'Sent' right way.After a few minutes when I opened up Email again, the whole email thread is there

**Comment by qlinkDev** [comment]
ios or Android？

**Comment by suuuju** [comment]
On iOS



发自我的iPhone


------------------ Original ------------------
